package es.udc.pojo.model.util;

import es.udc.pojo.model.sesion.Sesion;

/**
 * The Class CoincidentSesionsException.
 */
public class CoincidentSesionsException extends Exception {

    /** The s1. */
    private Sesion            s1;

    /** The s2. */
    private Sesion            s2;

    /** Autogenerated Code. */
    private static final long serialVersionUID = -1601965589090436959L;

    /**
     * Instantiates a new coincident sesions exception.
     *
     * @param s1
     *            the s1
     * @param s2
     *            the s2
     */
    public CoincidentSesionsException(Sesion s1, Sesion s2) {
        super("The following Sesions are coincident:" + s1 + " - " + s2);
        this.s1 = s1;
        this.s2 = s2;
    }

    /**
     * Gets the s1.
     *
     * @return the s1
     */
    public Sesion getS1() {
        return s1;
    }

    /**
     * Gets the s2.
     *
     * @return the s2
     */
    public Sesion getS2() {
        return s2;
    }

}
