package es.udc.pojo.model.util;

import es.udc.pojo.model.sesion.Sesion;

public class CoincidentSesionsException extends Exception {

    private Sesion            s1;
    private Sesion            s2;
    /**
     * Autogenerated Code
     */
    private static final long serialVersionUID = -1601965589090436959L;

    public CoincidentSesionsException(Sesion s1, Sesion s2) {
        super("The following Sesions are coincident:" + s1 + " - " + s2);
        this.s1 = s1;
        this.s2 = s2;
    }

    public Sesion getS1() {
        return s1;
    }

    public Sesion getS2() {
        return s2;
    }

}
